services:
  db18:
    image: postgres:16
    container_name: odoo18-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    tmpfs:
      - /var/lib/postgresql/data

  odoo18:
    build:
      context: .
      dockerfile: Dockerfile.test
      args:
        ODOO_VERSION: "18.0"
    container_name: odoo18-web
    depends_on:
      - db18
    ports:
      - "18069:8069"
    environment:
      HOST: db18
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./odoo_connector_rabbitmq:/mnt/extra-addons/odoo_connector_rabbitmq
    command: >
      odoo
      --db_host=db18 --db_user=odoo --db_password=odoo
      -d test18 -i odoo_connector_rabbitmq
      --test-enable --stop-after-init --log-level=test
      --without-demo=all
